In [2]:
pip install numpy --upgrade

  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.2
    Uninstalling numpy-1.19.2:
      Successfully uninstalled numpy-1.19.2
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\bapan\\anaconda3\\Lib\\site-packages\\~umpy\\core\\_multiarray_tests.cp38-win_amd64.pyd'
Consider using the `--user` option or check the permissions.



In [4]:
pip install tensorflow-text


  Using cached tensorflow_text-2.8.1-cp38-cp38-win_amd64.whl (2.5 MB)


In [1]:
import tensorflow as tf
print(tf.__version__)

2.7.0


In [2]:
import tensorflow_hub as hub
import tensorflow_text as text

In [2]:
tf.test.is_built_with_cuda()

True

In [4]:
import sys
sys.version

'3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]'

In [5]:
from platform import python_version
python_version()

'3.8.13'

In [6]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [7]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

OSError: SavedModel file does not exist at: C:\Users\bapan\AppData\Local\Temp\tfhub_modules\602d30248ff7929470db09f7385fc895e9ceb4c0\{saved_model.pbtxt|saved_model.pb}

In [86]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)
text_test = ['Where are you from?',
             'Where are you going?']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [87]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [88]:
text_preprocessed['input_type_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [89]:
text_preprocessed['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[ 101, 2073, 2024, 2017, 2013, 1029,  102,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],
       [ 101, 2073, 2024, 2017, 2183, 1029,  102,    0,    0,    0,    0,
           0,

#### 101 --> CLS token
#### 102 --> SEP token

##### BERT uses CLS as a special token at the begining of each setence whereas SEP as a special token to separate two sentences or end sinle sentece

In [90]:
bert_model = hub.KerasLayer(encoder_url)

In [91]:
bert_results = bert_model(text_preprocessed)

In [92]:
bert_results.keys()

dict_keys(['default', 'pooled_output', 'sequence_output', 'encoder_outputs'])

In [93]:
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 1.7691670e-02,  2.1396494e-01, -2.2290376e-01, ...,
         -4.4264150e-01,  2.3210651e-01,  3.4812185e-01],
        [ 4.5680231e-01, -9.6672094e-01,  2.8131533e-01, ...,
         -4.1544163e-01,  8.5898864e-01, -2.4606081e-02],
        [ 7.9660511e-01, -6.4747667e-01,  3.6817855e-01, ...,
         -8.0846816e-01,  2.6456103e-01, -3.3409774e-01],
        ...,
        [ 1.6598593e-01,  2.7767602e-01,  2.7768761e-01, ...,
         -4.0868483e-03, -1.2977324e-02, -4.4945944e-03],
        [ 7.1093187e-02,  1.9674021e-01,  2.7196085e-01, ...,
          4.6152506e-02,  7.0804678e-02,  7.6060556e-02],
        [ 1.7892782e-01,  1.2876679e-01,  3.2501581e-01, ...,
         -4.4548333e-02,  1.7056312e-02,  1.4583286e-02]],

       [[ 3.5457704e-02,  5.1742184e-01, -2.9451022e-01, ...,
         -4.3197721e-01,  2.1252400e-01,  4.2864415e-01],
        [-4.0797591e-02, -2.2484317e-01,  1.1920020e-02, ...,
         -7.1128851e-01,  4.

In [94]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.9362009 , -0.5720348 , -0.93059784, ..., -0.78182936,
        -0.79817086,  0.9492021 ],
       [-0.9493104 , -0.46768823, -0.92918175, ..., -0.7001574 ,
        -0.76068974,  0.9628811 ]], dtype=float32)>

In [95]:
output = bert_results['pooled_output'].numpy()
output.shape

(2, 768)

In [60]:
from sklearn.metrics.pairwise import cosine_similarity

In [96]:
cosine_similarity([output[0]],[output[1]])

array([[0.9957825]], dtype=float32)

In [21]:
len(bert_results['encoder_outputs'])

12

In [22]:
bert_results['encoder_outputs'][-1] == bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>

In [24]:
bert_results['encoder_outputs'][0]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.12901425,  0.00644747, -0.0361497 , ...,  0.04999633,
          0.06149192, -0.02657545],
        [ 1.1753384 ,  1.2140784 ,  1.1569979 , ...,  0.11634396,
         -0.35855335, -0.40490183],
        [ 0.03859033,  0.5386997 , -0.21089774, ...,  0.21858189,
          0.72601664, -1.1158603 ],
        ...,
        [-0.07587016, -0.254219  ,  0.7075511 , ...,  0.50541997,
         -0.1887868 ,  0.15028326],
        [-0.16066611, -0.28089687,  0.57597065, ...,  0.52758545,
         -0.11141388,  0.02887545],
        [-0.04428154, -0.20279586,  0.5909355 , ...,  0.8133835 ,
         -0.39075807, -0.02601737]],

       [[ 0.18903585,  0.02752546, -0.06513744, ..., -0.00620212,
          0.15053892,  0.03165444],
        [ 0.5916151 ,  0.7589137 , -0.07240665, ...,  0.6190394 ,
          0.8292891 ,  0.16161951],
        [ 1.4460827 ,  0.44602644,  0.4099025 , ...,  0.48255914,
          0.62691146,  0.13463417],
        ...,

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
%matplotlib inline

In [10]:
data = pd.read_csv('D:/NLP_DataSets/Sentiment_Analysis/Tweet_data.csv')

In [11]:
data = data.drop('Unnamed: 0', axis=1)

In [12]:
data['sentiment'].replace({'Negative':0, 'Positive':1}, inplace=True)

In [13]:
data.head(3)

tweet  sentiment
0  this is disgusting #grandmother #grandsons   #...          0
1  my all time favorite princess outfit 💙💗ð...          1
2    #fridayfeeling in the winery today with a fu...          1

In [14]:
data.shape

(22735, 2)

In [15]:
data['sentiment'].value_counts(normalize=True)

1    0.527821
0    0.472179
Name: sentiment, dtype: float64

In [16]:
X_train, X_valid, y_train, y_valid = train_test_split(data['tweet'], data['sentiment'],test_size=0.11, 
                                                    stratify=data['sentiment'].values, random_state=1)

In [17]:
X_train.shape, X_valid.shape

((20234,), (2501,))

In [36]:
# train_df['sentiment'].value_counts(normalize=True)

In [37]:
# valid_df['sentiment'].value_counts(normalize=True)

In [38]:
# with tf.device('/cpu:0'):
    
#     train_data = tf.data.Dataset.from_tensor_slices((train_df['tweet'].values, train_df['sentiment'].values))
#     valid_data = tf.data.Dataset.from_tensor_slices((valid_df['tweet'].values, valid_df['sentiment'].values))

#     for text, label in train_data.take(1):
#         print(text)
#         print(label)

In [23]:
# import sys
# sys.path.append('models')
# from official.nlp.data import classifier_data_lib
# from official.nlp.bert import tokenization
# from official.nlp import optimization

In [24]:
# """
# Each line of the dataset is composed of the review text and its label
# - Data preprocessing consists of transforming text to BERT input features:
# input_word_ids, input_mask, segment_ids
# - In the process, tokenizing the text is done with the provided BERT model tokenizer
# """

# label_list = [0,1]  # Label categories
# max_seq_length = 128  # maximum length of (token) input sequences
# train_batch_size = 32

# # Get BERT layer and tokenizer:
# # More details here: https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/2
# bert_layer = hub.KerasLayer('https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/2',
#                             trainable=True)
# vocab_file = bert_layer.resolved_object.vocab_file.asset_path.numpy()
# do_lower_case = bert_layer.resolved_object.do_lower_case.numpy()
# tokenizer = tokenization.FullTokenizer(vocab_file, do_lower_case)

In [18]:
bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4") 
                             # trainable=True)

In [19]:
def get_sentence_embeding(sentences):
    preprocessed_text = bert_preprocess(sentences)
    return bert_encoder(preprocessed_text)['pooled_output']

get_sentence_embeding([
    "500$ discount. hurry up", 
    "Bhavin, are you up for a volleybal game tomorrow?"]
)

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.84351707, -0.51327264, -0.8884571 , ..., -0.7474885 ,
        -0.75314736,  0.91964495],
       [-0.87208354, -0.5054397 , -0.94446677, ..., -0.8584749 ,
        -0.7174535 ,  0.88082975]], dtype=float32)>

In [20]:
e = get_sentence_embeding([
    "banana", 
    "grapes",
    "mango",
    "jeff bezos",
    "elon musk",
    "bill gates"
]
)

In [21]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity([e[0]],[e[1]])

array([[0.9911088]], dtype=float32)

In [46]:
# Bert layers
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text')
preprocessed_text = bert_preprocess(text_input)
outputs = bert_encoder(preprocessed_text)

# Neural network layers
l = tf.keras.layers.Dropout(0.1, name="dropout")(outputs['pooled_output'])
l = tf.keras.layers.Dense(1, activation='sigmoid', name="output")(l)

# Use inputs and outputs to construct a final model
model = tf.keras.Model(inputs=[text_input], outputs = [l])

In [19]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 text (InputLayer)              [(None,)]            0           []                               
                                                                                                  
 keras_layer (KerasLayer)       {'input_mask': (Non  0           ['text[0][0]']                   
                                e, 128),                                                          
                                 'input_word_ids':                                                
                                (None, 128),                                                      
                                 'input_type_ids':                                                
                                (None, 128)}                                                  

In [47]:
METRICS = [
      tf.keras.metrics.BinaryAccuracy(name='accuracy'),
      tf.keras.metrics.Precision(name='precision'),
      tf.keras.metrics.Recall(name='recall')
]

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=METRICS)

In [48]:
epochs = 2
history = model.fit(X_train, y_train, 
                    validation_data=(X_valid, y_valid), 
                    epochs=epochs)

Epoch 1/2
633/633 [==============================] - 3224s 5s/step - loss: 0.4951 - accuracy: 0.7798 - precision: 0.7802 - recall: 0.8115 - val_loss: 0.3982 - val_accuracy: 0.8473 - val_precision: 0.8212 - val_recall: 0.9083
Epoch 2/2
190/633 [========>.....................] - ETA: 33:26 - loss: 0.4083 - accuracy: 0.8419 - precision: 0.8438 - recall: 0.8583

KeyboardInterrupt: 